### ISSUE TITLE
Diff

### ISSUE THREAD

**Issue by mbtools** [sbcgua/ajson#18]
I implemented a diff including test case.

https://github.com/mbtools/ajson/commit/d1502b0a60959189ed836939e5e0792daa0b0aff

The current use case is to find out what changed in abaplint.json or what's the difference to the default abaplint.json. 

Issues:
- It's a bit too much code since "set" does not take "type" from the JSON node as input and I had to repeat the set logic 3x. 
- "set" will always create the path using type "object". How do I set a node to be "array"?
- The "save as..." part of the code could be much simpler if we had a "set_with_type" method to insert directly without interpreting the type of "iv_val" (meaning iv_val and iv_type match the internal node value). 

```
eo_change->set_with_type( iv_path         = <ls_node_b>-path && <ls_node_b>-name && '/'
                          iv_val          = <ls_node_b>-value
                          iv_type         = <ls_node_b>-type
                          iv_ignore_empty = iv_ignore_empty ).
```

Probably needs some tuning/testing like dealing with empty arrays.

Let me know if you want a PR.

**Comment by sbcgua** [comment]
Let's split into parts :))

1) `set_with_type` - could be nice. I think there are different scenarios where separate setter or `with_type` would be preferable. So why not, let's add it (a new method I mean). PR welcomed actually should be just wrapper around existing methods. Just please with UTs and docs (a simple example would be enough) :) 🙏 

2) Arrays. `set` should allow specifying tables as parameters. Otherwise it is a bug. Do you have an example ? Empty arrays are created with `touch_array`. `set_with_type` with type = array and empty value may just call it internally. 
BTW there are unit tests for touch_array - [have a look](https://github.com/sbcgua/ajson/blob/master/src/zcl_ajson.clas.testclasses.abap#L1728)

3) Diff - do you also propose to include this one ? This is a bit more controversial. But the feature itself is nice. However I'd propose to make it a separate utility class. It is an utility in fact.

**Comment by mbtools** [comment]
Coming back to this... I have implemented `set_with_type`. The test recursively copies the sample json to a new json using `set_with_type`. The result must be identical to the original.

https://github.com/mbtools/ajson/tree/set_with_type

I added new methods to the local class but you can see there's quite a bit of overlap between `set` and `set_with_type`. Might be nicer to merge the logic together. 

There's also a utility class for the diff with unit test.

**Comment by sbcgua** [comment]
had a quick look. I have to check it in more details. Briefly:
- set & set_with_type - probably yes, could be merged, just to keep it readable, I think will need to separate some parts e.g. validation. And iv_type should be probably iv_force_type or iv_use_type (which are actually semantically different ... e.g. type = string, value = 1 - would it result in raise or "1" ?)
- global friends with utils. pls no :) But I have no objection against exposing the read-only attr. I think they are abap power feature :)
- diff util - looks cool on the first glance

**Comment by sbcgua** [comment]
added `get_node_type` by the way - https://github.com/sbcgua/ajson/pull/26

**Comment by mbtools** [comment]
- you called in `rv_node_type` in the get. so `iv_node_type` would make sense for `set_with_type`
- agree, read-only for the node table is the way to go

**Comment by sbcgua** [comment]
- moved `mt_json_tree` to public. 
- `iv_node_type` - yeap, agree

So, do you want to PR or do you want me to adjust `set` to support node_type ? (if PR, pls separate from diff util to keep it focused)

**Comment by mbtools** [comment]
make your adjustments to the existing class. I will then do a PR for the diff with an example for the readme

**Comment by mbtools** [comment]
Let's see if these PRs work. Feel free to change, of course.

**Comment by sbcgua** [comment]
can be closed ?

**Comment by mbtools** [comment]
yes. thanks for merging 👍
